### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by emilio-martinez** [emilio-martinez/emc-webcomponents#1]
## Tasks
- [ ] Create elements
- [ ] Capabilities
    - [ ] Justification (start, center, end, fill, justified)
    - [ ] Disabled tabs
    - [ ] RTL
- [ ] Unit tests
- [ ] E2E tests
- [ ] Browser compat
- [ ] Demo page
    - [ ] Showcase attributes/variations
    - [ ] Different styling use cases (e.g., vertical tabs)

## References
- [WAI ARIA Authoring Practices - Tab Panel](https://www.w3.org/TR/wai-aria-practices/#tabpanel)
    - [Tabs with Automatic Activation](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/tabs/tabs-1/tabs.html)
    - [Example of Tabs with Manual Activation](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/tabs/tabs-2/tabs.html)
- [Léonie Watson - Danger! Testing Accessibility with real people](https://medium.com/@LeonieWatson/danger-testing-accessibility-with-real-people-4515f72db648)
- [Heydon Pickering - Practical ARIA Examples](http://heydonworks.com/practical_aria_examples/#tab-interface)
- [Athena Technologies - Tab panel](http://accessibility.athena-ict.com/aria/examples/tabpanel2.shtml)
- [MDC Tabs](https://github.com/material-components/material-components-web/tree/master/packages/mdc-tabs)
- [Angular Material Tabs](https://material.angular.io/components/tabs/examples)
